# 绾夸笂閰嶇疆鏂囦欢妯℃澘
# @author <a href="https://github.com/liyupi">绋嬪簭鍛橀奔鐨?/a>
# @from <a href="https://codefather.cn">缂栫▼瀵艰埅</a>
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<Your IP>:3306/babystep_ai_code_mother
    username: babystep_ai_code_mother_user
    password: 12345678
  # redis
  data:
    redis:
      host: <Your IP>
      port: 6379
      database: 0
      password: 12345678
      ttl: 3600
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <your-api-key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: false
      log-responses: false
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <your-api-key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: false
      log-responses: false
    # 鎺ㄧ悊 AI 妯″瀷閰嶇疆锛堢敤浜庡鏉傜殑鎺ㄧ悊浠诲姟锛?
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <your-api-key>
      model-name: deepseek-chat
      max-tokens: 8192
      temperature: 0.1
      log-requests: false
      log-responses: false
    # 鏅鸿兘璺敱 AI 妯″瀷閰嶇疆
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <your-api-key>
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: false
      log-responses: false
# 娣诲姞 COS 瀵硅薄瀛樺偍閰嶇疆锛堥渶瑕佷粠鑵捐浜戣幏鍙栵級
cos:
  client:
    host: <your-custom-domain.com>
    secretId: <your-secret-id>
    secretKey: <your-secret-key>
    region: <your-region>
    bucket: <your-bucket-name>
# 闃块噷浜?DashScope 閰嶇疆
dashscope:
  api-key: <your-api-key>
  image-model: wan2.2-t2i-flash
# Pexels 鍥剧墖鎼滅储閰嶇疆
pexels:
  api-key: <your-api-key>
# 鐢熶骇鐜鍏抽棴鏃ュ織
mybatis-flex:
  configuration:
    log-impl: ''
# 鎺ュ彛鏂囨。閰嶇疆
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
# 閮ㄧ讲璺緞
code:
  deploy-host: http://<Your IP>/dist

